1.3.1 Задание: Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [ ]:
import numpy as np

matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

1.3.2 Задание: Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [1]:
import numpy as np

a = np.array([np.arange(5)] * 5)

print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

1.3.3 Задание: Создать массив 3x3x3 со случайными значениями.

In [ ]:
import random
import numpy as np

x = np.random.random((3, 3, 3))

print(x)

[[[0.75325292 0.78358784 0.62454429]
  [0.09607231 0.82771396 0.55209837]
  [0.58602951 0.44364731 0.47177747]]

 [[0.20562671 0.58790241 0.13238078]
  [0.55241866 0.33087602 0.66175857]
  [0.29191956 0.76182208 0.132423  ]]

 [[0.02092182 0.45939345 0.81914282]
  [0.31837484 0.13040819 0.813353  ]
  [0.55979074 0.5752071  0.044481  ]]]

1.3.4 Задание: Создать матрицу с 0 внутри, и 1 на границах.

In [ ]:
import numpy as np

n = 8
x = np.zeros((n, n), dtype=int)
for i in range(n):
  if i==0 or i==(n-1):
    x[i] = np.array([1]*n)
  else:
    for j in range(n):
      if j ==0 or j==(n-1):
        x[i][j] = 1

print(x)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]

1.3.5 Задание: Создайте массив и отсортируйте его по убыванию

In [ ]:
import random
import numpy as np

x = np.random.random((5))

print(x)

x = np.sort(x)
x = x[::-1]

print(x)

[0.72216578 0.18751847 0.60051648 0.45273373 0.07835481]
[0.72216578 0.60051648 0.45273373 0.18751847 0.07835481]

1.3.6 Задание: Создайте матрицу, выведите ее форму, размер и размерность.

In [ ]:
import random
from random import randint
import numpy as np

x = np.random.random((randint(0, 10), randint(0, 10)))
print(x)
dim = np.shape(x)
if dim[0] == dim[1]:
  print("Квадратная")
else:
  print("Прямоугольная")
print("Размер: ", np.size(x))
print("Размерность: ", dim)

[[0.14125402 0.44708594]
 [0.54994221 0.69317116]
 [0.10887177 0.36322947]
 [0.54495354 0.14637189]]
Прямоугольная
Размер:  8
Размерность:  (4, 2)

2.3.1 Задание: Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [ ]:
import pandas as pd
import numpy as np

p1 = pd.Series([1, 2, 3])
p2 = pd.Series([1, 2, 1])

print(np.sqrt((p1[0]-p2[0])**2+(p1[1]-p2[1])**2+(p1[2]-p2[2])**2))

2.0

2.3.2 Задание: Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets)

In [ ]:
import pandas as pd

dataframe = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/main/airlines.csv')

print(dataframe)

       Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0           CO     269         SFO       IAH          3    15     205      1
1           US    1558         PHX       CLT          3    15     222      1
2           AA    2400         LAX       DFW          3    20     165      1
3           AA    2466         SFO       DFW          3    20     195      1
4           AS     108         ANC       SEA          3    30     202      0
...        ...     ...         ...       ...        ...   ...     ...    ...
539378      CO     178         OGG       SNA          5  1439     326      0
539379      FL     398         SEA       ATL          5  1439     305      0
539380      FL     609         SFO       MKE          5  1439     255      0
539381      UA      78         HNL       SFO          5  1439     313      1
539382      US    1442         LAX       PHL          5  1439     301      1

[539383 rows x 8 columns]

2.3.3 Задание:
Пронализировать характеристики фрейма данных.
Выберите индивидуальные данные или срезы фрейма данных.
Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из Airline AS

In [ ]:
import pandas as pd

dataframe = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/main/airlines.csv')

print(dataframe.head(2))
print(dataframe.tail(3))
print(dataframe.shape)
print(dataframe.describe())

print(dataframe.iloc[65:68])

aass = dataframe[dataframe['Airline']=='AS']
print(aass)

  Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
       Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
539380      FL     609         SFO       MKE          5  1439     255      0
539381      UA      78         HNL       SFO          5  1439     313      1
539382      US    1442         LAX       PHL          5  1439     301      1
(539383, 8)
              Flight      DayOfWeek           Time         Length  \
count  539383.000000  539383.000000  539383.000000  539383.000000
mean     2427.928630       3.929668     802.728963     132.202007
std      2067.429837       1.914664     278.045911      70.117016
min         1.000000       1.000000      10.000000       0.000000
25%       712.000000       2.000000     565.000000      81.000000
50%      1809.000000       4.000000     795.000000     115.000000
75%      3745.000000       5.000000    1035.000000     162.000000
max      7814.000000       7.000000    1439.000000     655.000000

               Delay
count  539383.000000
mean        0.445442
std         0.497015
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000
   Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
65      DL    2112         BHM       ATL          3   330      58      0
66      DL    2306         LIT       ATL          3   330      97      0
67      DL    2711         SAV       ATL          3   330      65      0
       Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
4           AS     108         ANC       SEA          3    30     202      0
14          AS     132         ANC       PDX          3    55     215      0
20          AS     128         FAI       SEA          3    80     206      0
22          AS     112         ANC       SEA          3    90     200      0
25          AS     114         ANC       SEA          3   150     200      0
...        ...     ...         ...       ...        ...   ...     ...    ...
539229      AS      52         FAI       ANC          5  1340      57      0
539240      AS      16         SEA       MIA          5  1345     335      1
539293      AS      10         SEA       MCO          5  1365     319      0
539330      AS     698         SEA       GEG          5  1380      58      0
539346      AS     138         ANC       ORD          5  1405     345      0

[11471 rows x 8 columns]

3.3.2 Задание: Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

dataframe = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')

scaler_minmax = MinMaxScaler()
dataframe['sepal_length_cm'] = scaler_minmax.fit_transform(dataframe[['sepal_length_cm']])

scaler_zscore = StandardScaler()
dataframe['sepal_width_cm'] = scaler_zscore.fit_transform(dataframe[['sepal_width_cm']])

print(dataframe)

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2
1           0.166667       -0.124958              1.4             0.2
2           0.111111        0.337848              1.3             0.2
3           0.083333        0.106445              1.5             0.2
4           0.194444        1.263460              1.4             0.2
..               ...             ...              ...             ...
145         0.666667       -0.124958              5.2             2.3
146         0.555556       -1.281972              5.0             1.9
147         0.611111       -0.124958              5.2             2.0
148         0.527778        0.800654              5.4             2.3
149         0.444444       -0.124958              5.1             1.8

       species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 5 columns]